apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: webapp
      env: production
   name:  httpd-frontend
spec:
   replicas: 3
   selector:
      matchLabels:
         color: blue
   template:
     metadata:
        labels:
           color: blue
           env: production
        name: mypod-d
     spec:
       containers:
         - image: nginx
           name: nginx-c
           ports:
             - containerPort: 80
       affinity:
         nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In
                  values:
                  - blue
             
